# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  GlApp_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  GlApp_config = release
endif
ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  GlApp_config = dist
endif

PROJECTS := GLFW Glad GlApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C GlApp/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C GlApp/vendor/Glad -f Makefile config=$(Glad_config)
endif

GlApp: GLFW Glad
ifneq (,$(GlApp_config))
	@echo "==== Building GlApp ($(GlApp_config)) ===="
	@${MAKE} --no-print-directory -C GlApp -f Makefile config=$(GlApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C GlApp/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C GlApp/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C GlApp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   GlApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"